# Generated by Django 2.1.5 on 2019-02-13 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190206_0728'),
        ('accounts', '0002_auto_20190211_2017'),
    ]

    operations = [
    ]
